apiVersion: v1
kind: Service
metadata:
  name: consumer-logger
  labels:
    app.kubernetes.io/created-by: tester
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: ¿http or 9000?
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: consumer-logger
    app.kubernetes.io/instance: consumer-logger
    app.kubernetes.io/component: service