// Package strategies provides the strategy framework for trading strategies.
package strategies

import (
	"context"
	"time"

	"bitso-trading-platform/strategy-executor/internal/indicators"
)

// Signal represents a trading signal generated by a strategy
type Signal struct {
	Strategy   string                 `json:"strategy"`
	Book       string                 `json:"book"`
	Side       string                 `json:"side"`
	Amount     float64                `json:"amount"`
	Price      float64                `json:"price"`
	Confidence float64                `json:"confidence"`
	Reason     string                 `json:"reason"`
	Timestamp  time.Time              `json:"timestamp"`
	Metadata   map[string]interface{} `json:"metadata,omitempty"`
}

// StrategyState represents the current state of a strategy
type StrategyState struct {
	Name            string    `json:"name"`
	Running         bool      `json:"running"`
	HasPosition     bool      `json:"has_position"`
	PositionSide    string    `json:"position_side,omitempty"`
	PositionSize    float64   `json:"position_size"`
	EntryPrice      float64   `json:"entry_price,omitempty"`
	EntryTime       time.Time `json:"entry_time,omitempty"`
	UnrealizedPnL   float64   `json:"unrealized_pnl"`
	LastSignalTime  time.Time `json:"last_signal_time,omitempty"`
	SignalCount     int64     `json:"signal_count"`
	TradeCount      int64     `json:"trade_count"`
	WinCount        int64     `json:"win_count"`
	LossCount       int64     `json:"loss_count"`
	ConsecutiveLoss int       `json:"consecutive_loss"`
	// PendingBuy is true after a BUY signal was emitted but before a fill was confirmed (limit_profit).
	PendingBuy bool `json:"pending_buy,omitempty"`
	// PendingBuySince records when the pending BUY was emitted (for pending_buy_timeout_seconds).
	PendingBuySince time.Time `json:"pending_buy_since,omitempty"`
	// PendingEventID is the TradeSignalEvent.event_id for the open BUY (used to match fill callbacks).
	PendingEventID string `json:"pending_event_id,omitempty"`
	// PendingSell is true after a SELL signal was emitted but before the exchange fill is confirmed.
	// While true, OnTick must not emit new signals (prevents order stacking).
	PendingSell bool `json:"pending_sell,omitempty"`
	// PendingSellSince records when the pending SELL was emitted (for pending_sell_timeout_seconds).
	PendingSellSince time.Time `json:"pending_sell_since,omitempty"`
	// PendingSellEventID is the TradeSignalEvent.event_id for the open SELL (used to match fill callbacks).
	PendingSellEventID string `json:"pending_sell_event_id,omitempty"`
}

// StrategyMetrics represents performance metrics for a strategy
type StrategyMetrics struct {
	TotalPnL          float64   `json:"total_pnl"`
	DailyPnL          float64   `json:"daily_pnl"`
	MaxDrawdown       float64   `json:"max_drawdown"`
	DrawdownPercent   float64   `json:"drawdown_percent"`
	WinRate           float64   `json:"win_rate"`
	ProfitFactor      float64   `json:"profit_factor"`
	SharpeRatio       float64   `json:"sharpe_ratio"`
	AvgTradeDuration  float64   `json:"avg_trade_duration_seconds"`
	TradesPerDay      float64   `json:"trades_per_day"`
	LastUpdated       time.Time `json:"last_updated"`
}

// StrategyConfig holds configuration for a strategy
type StrategyConfig struct {
	Name              string                 `json:"name" yaml:"name"`
	Type              string                 `json:"type" yaml:"type"`
	Version           string                 `json:"version" yaml:"version"`
	Enabled           bool                   `json:"enabled" yaml:"enabled"`
	Book              string                 `json:"book" yaml:"book"`
	Parameters        map[string]interface{} `json:"parameters" yaml:"parameters"`
	Sizing            SizingConfig           `json:"sizing" yaml:"sizing"`
	Risk              RiskConfig             `json:"risk" yaml:"risk"`
	Schedule          ScheduleConfig         `json:"schedule" yaml:"schedule"`
}

// SizingConfig holds position sizing configuration
type SizingConfig struct {
	Method           string  `json:"method" yaml:"method"`
	MaxPositionSize  float64 `json:"max_position_size" yaml:"max_position_size"`
	MaxPositionValue float64 `json:"max_position_value" yaml:"max_position_value"`
}

// ResolvePositionSize uses parameters.position_size when set, otherwise sizing.max_position_size
// or defaultSize. MaxPositionSize is a ceiling, not an unconditional override.
func ResolvePositionSize(parameters map[string]interface{}, maxPositionSize float64, defaultSize float64) float64 {
	size := defaultSize
	paramSet := false
	if parameters != nil {
		if v, ok := parameters["position_size"].(float64); ok && v > 0 {
			size = v
			paramSet = true
		}
	}
	if !paramSet && maxPositionSize > 0 {
		size = maxPositionSize
	}
	if maxPositionSize > 0 && size > maxPositionSize {
		size = maxPositionSize
	}
	return size
}

// RiskConfig holds risk management configuration
type RiskConfig struct {
	MaxDailyLoss        float64 `json:"max_daily_loss" yaml:"max_daily_loss"`
	MaxDrawdownPct      float64 `json:"max_drawdown_pct" yaml:"max_drawdown_pct"`
	MaxTradesPerDay     int     `json:"max_trades_per_day" yaml:"max_trades_per_day"`
	MaxConsecutiveLoss  int     `json:"max_consecutive_losses" yaml:"max_consecutive_losses"`
	MinTimeBetweenTrades int    `json:"min_time_between_trades" yaml:"min_time_between_trades"`
	CooldownAfterLoss   int     `json:"cooldown_after_loss" yaml:"cooldown_after_loss"`
}

// ScheduleConfig holds trading schedule configuration
type ScheduleConfig struct {
	ActiveHours string   `json:"active_hours" yaml:"active_hours"`
	Timezone    string   `json:"timezone" yaml:"timezone"`
	ActiveDays  []string `json:"active_days" yaml:"active_days"`
}

// EnhancedStrategy defines the contract for all trading strategies
type EnhancedStrategy interface {
	Name() string
	Version() string

	Initialize(config StrategyConfig, indicatorSvc *indicators.Service) error
	Start(ctx context.Context) error
	Stop() error
	Reset()

	OnTick(tick *indicators.Trade) (*Signal, error)
	OnBar(bar *indicators.OHLCV) (*Signal, error)

	GetState() StrategyState
	GetMetrics() StrategyMetrics
	GetConfig() StrategyConfig

	IsRunning() bool
	IsWithinSchedule() bool
}

// OrderFill describes an exchange fill for OrderFillAware strategies.
// Optional fields let order-management map actual maker/taker or measured fee rates.
type OrderFill struct {
	EventID      string   `json:"event_id"`
	Book         string   `json:"book"`
	Side         string   `json:"side"`
	AveragePrice float64  `json:"average_price"`
	FilledAmount float64  `json:"filled_amount"`
	Liquidity    string   `json:"liquidity,omitempty"`    // "maker" | "taker" — role when the fill executed
	BuyFeeRate   *float64 `json:"buy_fee_rate,omitempty"` // legacy BUY-leg override; prefer FeeRate
	// FeeRate is the realized decimal fraction of notional for *this fill leg* (e.g. 0.00741 = 0.741%).
	// Populated by order-management from Bitso UserTrade. Strategies that track per-leg fees
	// should prefer this over the configured maker/taker assumption. See docs/strategy-fee-accuracy/.
	FeeRate float64 `json:"fee_rate,omitempty"`
}

// OrderFillAware strategies open a position only after an exchange fill is reported for the BUY signal.
// Correlation uses the same event_id published on trading.signals (metadata.event_id).
type OrderFillAware interface {
	OnOrderFilled(fill OrderFill)
}

// LimitProfitRawStateStore persists limit_profit mutex-held state (e.g. Redis) as opaque JSON.
type LimitProfitRawStateStore interface {
	Save(ctx context.Context, strategyName string, payload []byte) error
	Load(ctx context.Context, strategyName string) ([]byte, error)
	Delete(ctx context.Context, strategyName string) error
}

// PendingBuyCancelClient requests order-management to cancel a resting entry order by signal event_id (optional).
type PendingBuyCancelClient interface {
	CancelOrderBySignalID(ctx context.Context, signalID string) error
}

// EnhancedStrategyFactory creates enhanced strategy instances
type EnhancedStrategyFactory func() EnhancedStrategy

// BaseEnhancedStrategy provides common functionality for strategies
type BaseEnhancedStrategy struct {
	name         string
	version      string
	config       StrategyConfig
	indicatorSvc *indicators.Service
	state        StrategyState
	metrics      StrategyMetrics
	running      bool
}

// NewBaseEnhancedStrategy creates a new base strategy
func NewBaseEnhancedStrategy(name, version string) *BaseEnhancedStrategy {
	return &BaseEnhancedStrategy{
		name:    name,
		version: version,
		state:   StrategyState{Name: name},
	}
}

func (s *BaseEnhancedStrategy) Name() string {
	return s.name
}

func (s *BaseEnhancedStrategy) Version() string {
	return s.version
}

func (s *BaseEnhancedStrategy) Initialize(config StrategyConfig, indicatorSvc *indicators.Service) error {
	s.config = config
	if config.Name != "" {
		s.name = config.Name
	}
	s.indicatorSvc = indicatorSvc
	s.state = StrategyState{Name: s.name}
	s.metrics = StrategyMetrics{}
	return nil
}

func (s *BaseEnhancedStrategy) Start(ctx context.Context) error {
	s.running = true
	s.state.Running = true
	return nil
}

func (s *BaseEnhancedStrategy) Stop() error {
	s.running = false
	s.state.Running = false
	return nil
}

func (s *BaseEnhancedStrategy) Reset() {
	s.state = StrategyState{Name: s.name}
	s.metrics = StrategyMetrics{}
}

// ApplyPersistedState restores strategy state from durable storage (limit_profit Redis snapshot).
func (s *BaseEnhancedStrategy) ApplyPersistedState(st StrategyState) {
	st.Name = s.name
	s.state = st
}

func (s *BaseEnhancedStrategy) GetState() StrategyState {
	return s.state
}

func (s *BaseEnhancedStrategy) GetMetrics() StrategyMetrics {
	return s.metrics
}

func (s *BaseEnhancedStrategy) GetConfig() StrategyConfig {
	return s.config
}

func (s *BaseEnhancedStrategy) IsRunning() bool {
	return s.running
}

func (s *BaseEnhancedStrategy) IsWithinSchedule() bool {
	return true
}

// UpdateState updates the strategy state
func (s *BaseEnhancedStrategy) UpdateState(update func(*StrategyState)) {
	update(&s.state)
}

// UpdateMetrics updates the strategy metrics
func (s *BaseEnhancedStrategy) UpdateMetrics(update func(*StrategyMetrics)) {
	update(&s.metrics)
	s.metrics.LastUpdated = time.Now()
}

// RecordSignal records a signal generation
func (s *BaseEnhancedStrategy) RecordSignal() {
	s.state.SignalCount++
	s.state.LastSignalTime = time.Now()
}

// RecordTrade records a trade without updating P&L metrics (kept for backward compatibility).
// New call sites should use RecordTradeWithPnL to ensure TotalPnL/DailyPnL reflect realized results.
func (s *BaseEnhancedStrategy) RecordTrade(profitable bool) {
	s.RecordTradeWithPnL(profitable, 0)
}

// RecordTradeWithPnL records a trade and accumulates realizedPnL into TotalPnL/DailyPnL.
// realizedPnL is in quote currency: positive = profit, negative = loss. May be 0 for signal-only
// pipelines where P&L is tracked elsewhere.
func (s *BaseEnhancedStrategy) RecordTradeWithPnL(profitable bool, realizedPnL float64) {
	s.state.TradeCount++
	if profitable {
		s.state.WinCount++
		s.state.ConsecutiveLoss = 0
	} else {
		s.state.LossCount++
		s.state.ConsecutiveLoss++
	}

	if s.state.TradeCount > 0 {
		s.metrics.WinRate = float64(s.state.WinCount) / float64(s.state.TradeCount)
	}

	s.metrics.TotalPnL += realizedPnL
	s.metrics.DailyPnL += realizedPnL
	s.metrics.LastUpdated = time.Now()
}

// SetPosition sets the current position
func (s *BaseEnhancedStrategy) SetPosition(side string, size, price float64) {
	s.state.HasPosition = true
	s.state.PositionSide = side
	s.state.PositionSize = size
	s.state.EntryPrice = price
	s.state.EntryTime = time.Now()
}

// ClearPosition clears the current position
func (s *BaseEnhancedStrategy) ClearPosition() {
	s.state.HasPosition = false
	s.state.PositionSide = ""
	s.state.PositionSize = 0
	s.state.EntryPrice = 0
	s.state.EntryTime = time.Time{}
}

// GetIndicatorService returns the indicator service
func (s *BaseEnhancedStrategy) GetIndicatorService() *indicators.Service {
	return s.indicatorSvc
}
