package varmodel

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"sort"
	"testing"
)

var updateEpisodes = flag.Bool("update-episodes", false, "rewrite episode_paths_gen.go from the committed Bitso CSVs")

// episodeCSVs are the committed Bitso histories the known paths come from.
var episodeCSVs = map[string]string{
	"btc_mxn": "evidence-2026-09-27/btc_mxn_daily_bitso.csv",
	"btc_usd": "evidence-2026-09-28/btc_usd_daily_bitso.csv",
}

func buildKnown(t *testing.T) map[string]map[string][]PathPoint {
	out := map[string]map[string][]PathPoint{}
	for book, f := range episodeCSVs {
		cs := readCloses(t, f)
		out[book] = map[string][]PathPoint{}
		for _, e := range Episodes {
			p, ok := EpisodePath(cs, e)
			if !ok {
				p = nil // known: no data for this episode
			}
			out[book][e.ID] = p
		}
	}
	return out
}

func renderKnown(known map[string]map[string][]PathPoint) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by go test -run TestKnownEpisodePathsMatchCSVs -update-episodes; DO NOT EDIT.\n\n")
	b.WriteString("package varmodel\n\n")
	b.WriteString("// KnownEpisodePaths are the books' paths through Episodes, computed from\n")
	b.WriteString("// the committed Bitso daily closes (docs/backtest-readiness/evidence-*).\n")
	b.WriteString("// A nil path means the book has no Bitso data for that episode. The past\n")
	b.WriteString("// does not change, so order-management starts from these instead of\n")
	b.WriteString("// fetching them after every restart (plan §6.4.10).\n")
	b.WriteString("var KnownEpisodePaths = map[string]map[string][]PathPoint{\n")
	books := make([]string, 0, len(known))
	for k := range known {
		books = append(books, k)
	}
	sort.Strings(books)
	for _, book := range books {
		fmt.Fprintf(&b, "%q: {\n", book)
		for _, e := range Episodes {
			p := known[book][e.ID]
			if p == nil {
				fmt.Fprintf(&b, "%q: nil,\n", e.ID)
				continue
			}
			fmt.Fprintf(&b, "%q: {\n", e.ID)
			for _, pt := range p {
				fmt.Fprintf(&b, "{Date: date(%q), Cum: %v},\n", pt.Date.Format("2006-01-02"), pt.Cum)
			}
			b.WriteString("},\n")
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	return src
}

// TestKnownEpisodePathsMatchCSVs fails when episode_paths_gen.go no longer
// matches the committed CSVs or Episodes (e.g. an episode was added).
// Regenerate with: go test ./pkg/varmodel -run TestKnownEpisodePathsMatchCSVs -update-episodes
func TestKnownEpisodePathsMatchCSVs(t *testing.T) {
	known := buildKnown(t)
	if *updateEpisodes {
		if err := os.WriteFile("episode_paths_gen.go", renderKnown(known), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	if !reflect.DeepEqual(known, KnownEpisodePaths) {
		t.Fatal("episode_paths_gen.go is stale; run: go test ./pkg/varmodel -run TestKnownEpisodePathsMatchCSVs -update-episodes")
	}
	for book, eps := range KnownEpisodePaths {
		if len(eps) != len(Episodes) {
			t.Errorf("%s: %d episodes known, want all %d", book, len(eps), len(Episodes))
		}
	}
}
