#!/usr/bin/env bash
# Generate k8s/monitoring/trading-risk-rules.yaml (a PrometheusRule for
# kube-prometheus-stack) from monitoring/prometheus/rules/trading-risk-alerts.yml,
# so the plain-Prometheus and the k8s copies never drift.
#
#   scripts/sync-prometheus-rules.sh          # rewrite the k8s file
#   scripts/sync-prometheus-rules.sh --check  # exit 1 if it is out of date (CI)
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
src="$root/monitoring/prometheus/rules/trading-risk-alerts.yml"
dst="$root/k8s/monitoring/trading-risk-rules.yaml"

render() {
  cat <<'EOF'
# GENERATED by scripts/sync-prometheus-rules.sh from
# monitoring/prometheus/rules/trading-risk-alerts.yml. Do not edit by hand.
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: trading-risk-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: kube-prometheus-stack
spec:
EOF
  # Everything from "groups:" on, indented under spec.
  sed -n '/^groups:/,$p' "$src" | sed 's/^/  /; s/^  $//'
}

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -u "$dst" <(render); then
    echo "k8s/monitoring/trading-risk-rules.yaml is out of date: run scripts/sync-prometheus-rules.sh" >&2
    exit 1
  fi
  echo "trading-risk-rules.yaml is in sync"
else
  render >"$dst"
  echo "wrote $dst"
fi
