apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - trading-engine.yaml
  - backtesting.yaml
  - strategy-executor.yaml
  - market-data.yaml
  - order-management.yaml
  - api-gateway.yaml

commonLabels:
  app: bitso-trading-platform
